on:
    push:
      branches:
        - main
      workflow_dispatch:
jobs:
    deploy:
        runs-on: self-hosted
        steps:
             - uses: actions/checkout@v2

             - name: change docker publish port
               run: sed -i 's/3000:3000/80:3000/g' docker-compose.yml

             - name: compose build
               run: docker compose build

             - name: compose up
               run: docker compose up -d
