on:
    push:
      branches:
        - main
      workflow_dispatch:
jobs:
    deploy:
        runs-on: amd2
        steps:
             - uses: actions/checkout@v2

             - name: compose build
               run: docker compose build

             - name: compose up
               run: docker compose up -d
